name: tsb_mini
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  font_awesome_flutter: ^10.10.0
  heroicons: ^0.11.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  path_provider: ^2.1.3

  tree_circle_progress:
    git:
      url: https://github.com/ritz-dev/tree_circle_progress.git
      ref: tree_circle_progress

  tsb_main:
    git:
      url: https://github.com/ritz-dev/tsb_main.git
      ref: staging




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/home_images/
    - assets/icon/
    - assets/image/
    - assets/logo/
    - assets/reward/
    - assets/tier/
    - assets/lang/

